<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>IdleMonitor</RootNamespace>
    <AssemblyName>IdleMonitor</AssemblyName>
    <ApplicationIcon>..\..\app.ico</ApplicationIcon>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
</Project>
